name: "Podcast Generator 2024"
author: "Kalani Herath"
description: "Generate a podcast from a list of mp3 files"
runs: 
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email: 
    description: "The commiter's Email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ github.actor }}